import type { Metadata } from "next";
import "./globals.css";
import NavLink from "@/components/navLink";
import { PlusSquare } from "@/assets/plusSquare";
import { User } from "@/assets/user";

export const metadata: Metadata = {
  title: "Next JS 15 Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900 antialiased flex flex-col items-center justify-center m-0 p-0">
        <h1 className="text-4xl font-bold text-center bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 bg-clip-text text-transparent mt-3">
          Welcome to Next.js 15 Demo!{" "}
        </h1>
        <nav className="w-full bg-white shadow-md border-b border-gray-200 py-3">
          <div className="max-w-2xl mx-auto flex justify-around text-gray-600 font-semibold">
            <NavLink href="/">
              <PlusSquare size={20} />
              <span>Add Post</span>
            </NavLink>
            <NavLink href="/profile">
              <User size={20} />
              <span>Profile</span>
            </NavLink>
          </div>
        </nav>
        <div className="w-[100%] bg-gray-100 flex items-center justify-center font-sans py-5">
          {children}
        </div>
      </body>
    </html>
  );
}
